serverConfig:
  node.environment: test
  http-server.http.port: 8080
  http-server.process-forwarded: true

routingRules:
  rulesEngineEnabled: True
  rulesConfigPath: "src/main/resources/rules/routing_rules.yml"
  rulesType: DATABASE

requestAnalyzerConfig:
  analyzeRequest: true

dataStore:
  jdbcUrl: jdbc:postgresql://localhost:5432/trino_gateway_db
  user: trino
  password: trino
  driver: org.postgresql.Driver
  queryHistoryHoursRetention: 24

clusterStatsConfiguration:
  monitorType: INFO_API

# This can be adjusted based on the coordinator state
monitor:
  taskDelay: 1m
  clusterMetricsRegistryRefreshPeriod: 30s
